build: false
os: Visual Studio 2015
platform:
  - x64
environment:
  matrix:
    - MINICONDA: C:\pybind11_json-conda
init:
  - "ECHO %MINICONDA%"
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%
  - ps: if($env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
  - cmd: C:\Miniconda.exe /S /D=C:\pybind11_json-conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"
  - ps: $env:PYTHONHOME = "C:\pybind11_json-conda"
install:
  # Install conda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install cmake python nlohmann_json=3.2.0 pybind11=2.2.4 -c conda-forge
  # Build
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -D CMAKE_INSTALL_PREFIX=%MINICONDA%\\LIBRARY -D DOWNLOAD_GTEST=ON -Dgtest_force_shared_crt=ON ..
  - nmake install
build_script:
  - .\test\test_pybind11_json
